// engine/workoutParser.js
// ---------------------------------------------------------
// Spirit v7 — Automatic Workout Plan Parser (Batch 4)
// Extracts structure (warmup, blocks, sets, reps, timing)
// from ANY workout plan generated by Spirit.
// ---------------------------------------------------------

export function parseWorkoutPlan(planText = "") {
  if (!planText || typeof planText !== "string") {
    return { ok: false, error: "Invalid plan text." };
  }

  const sections = {
    warmup: [],
    blocks: [],
    cooldown: [],
  };

  let currentBlock = null;

  // Split by lines for readability
  const lines = planText.split("\n").map((l) => l.trim());

  // Regex helpers
  const setRepRegex = /(\d+)\s*sets?[\s*xX]+(\d+)\s*reps?/i;
  const timingRegex = /(\d+)\s*(seconds?|sec|minutes?|mins?)/i;
  const exerciseLine = /^[-•]/;

  for (let line of lines) {
    // Identify section transitions
    if (/warm[-\s]*up/i.test(line)) {
      currentBlock = "warmup";
      continue;
    }
    if (/cool[-\s]*down/i.test(line)) {
      currentBlock = "cooldown";
      continue;
    }
    if (/^(block|circuit|day|round)/i.test(line)) {
      currentBlock = "block";
      sections.blocks.push({ title: line, exercises: [] });
      continue;
    }

    if (!currentBlock) continue;

    // Handle warmup/cooldown simple lines
    if (currentBlock === "warmup" || currentBlock === "cooldown") {
      if (exerciseLine.test(line)) {
        const parsed = parseExerciseLine(line);
        if (parsed) sections[currentBlock].push(parsed);
      }
      continue;
    }

    // Handle blocks
    if (currentBlock === "block") {
      if (exerciseLine.test(line)) {
        const parsed = parseExerciseLine(line);

        if (parsed) {
          const lastBlock = sections.blocks[sections.blocks.length - 1];
          lastBlock.exercises.push(parsed);
        }
      }
    }
  }

  return { ok: true, sections };
}

// ----------------------------------------------
// Single exercise parser
// ----------------------------------------------
function parseExerciseLine(line) {
  const name = line.replace(/^[-•]\s*/, "");

  const setRep = line.match(/(\d+)\s*sets?[\s*xX]+(\d+)\s*reps?/i);
  const timing = line.match(/(\d+)\s*(seconds?|sec|minutes?|mins?)/i);

  return {
    raw: line,
    name,
    sets: setRep ? Number(setRep[1]) : null,
    reps: setRep ? Number(setRep[2]) : null,
    time: timing ? `${timing[1]} ${timing[2]}` : null,
  };
}

// ----------------------------------------------
// Utility for Live Mode to get sequential blocks
// ----------------------------------------------
export function flattenWorkoutForLive(parsed) {
  if (!parsed?.ok) return [];

  const sequence = [];

  // Warmup
  parsed.sections.warmup.forEach((ex) =>
    sequence.push({ type: "warmup", ...ex })
  );

  // Blocks
  parsed.sections.blocks.forEach((block) => {
    sequence.push({ type: "block_header", title: block.title });
    block.exercises.forEach((ex) =>
      sequence.push({ type: "exercise", ...ex })
    );
  });

  // Cooldown
  parsed.sections.cooldown.forEach((ex) =>
    sequence.push({ type: "cooldown", ...ex })
  );

  return sequence;
}