from enum import Enum

class MechanismActivation(Enum):
    """47 mechanistic priors from Human Operating Model"""
    COGNITIVE_ENERGY_DEPLETION = 1
    SLEEP_DEBT_IMPAIRMENT = 2
    DECISION_FATIGUE = 3
    GLUCASE_STABILITY = 4
    STRESS_NARROWING = 5
    HIGH_AROUSAL_REACTIVE = 6
    FATIGUE_FAMILIARITY_BIAS = 7
    WORKING_MEMORY_OVERLOAD = 8
    AMBIGUITY_COST = 9
    TASK_SWITCHING_MOMENTUM = 10
    INTERRUPTION_RESET = 11
    COGNITIVE_FLUENCY_OPT = 12
    STORY_COMPRESSION = 13
    ATTENTION_RESIDUE = 14
    COMPLEXITY_PERCEPTION = 15
    PREDICTED_REWARD_FOLLOWING = 16
    PROGRESS_SIGNALS = 17
    IMMEDIATE_CERTAINTY_BIAS = 18
    EFFORT_ANTICIPATION = 19
    THREAT_PREDICTION_ERROR = 20
    NOVELTY_INITIATION = 21
    SMALL_WINS_PREFERENCE = 22
    COMPLETION_SATISFACTION_DECAY = 23
    AVOIDANCE_REINFORCEMENT = 24
    UNCERTAINTY_AS_THREAT = 25
    IDENTITY_DEFENSIVE_REASONING = 26
    SELF_EVALUATION_AMBIGUITY = 27
    SOCIAL_JUDGMENT_FEAR = 28
    UNCERTAINTY_NEUROLOGICAL_DANGER = 29
    LOSS_AVERSION_2X = 30
    SELF_COHERENCE_PROTECTION = 31
    BELIEF_UPDATE_FROM_EXPERIENCE = 32
    CONTRADICTORY_EVIDENCE_REINTERPRET = 33
    SMALL_CONSISTENT_SIGNALS = 34
    ACTION_FASTER_THAN_THOUGHT = 35
    TRAIT_INFERENCE_FROM_STATES = 36
    HABIT_CONTEXT_STABILITY = 37
    SOCIAL_OBSERVATION_EFFECT = 38
    IDENTITY_CONSISTENCY_OVERRIDE = 39
